Make test suite stable when `NO_COLOR` is set
```shell
$ env NO_COLOR=1 make test
go test -cpu 24 -race -count=1 -timeout=30s ./...
?   	github.com/evilmartians/lefthook/v2	[no test files]
?   	github.com/evilmartians/lefthook/v2/cmd	[no test files]
?   	github.com/evilmartians/lefthook/v2/gen	[no test files]
ok  	github.com/evilmartians/lefthook/v2/internal/command	1.081s
ok  	github.com/evilmartians/lefthook/v2/internal/config	1.050s
ok  	github.com/evilmartians/lefthook/v2/internal/git	1.018s
?   	github.com/evilmartians/lefthook/v2/internal/logger	[no test files]
?   	github.com/evilmartians/lefthook/v2/internal/run	[no test files]
--- FAIL: Test_guard_wrap (0.00s)
    --- FAIL: Test_guard_wrap/stashUnstagedChanges=true_failOnChanges=true_with_partially_staged_and_hook_changes_with_diff (0.00s)
        commander.go:122: 9) expected: 'git diff --color -- file1', called: 'git diff -- file1'
    --- FAIL: Test_guard_wrap/failOnChanges=true_fail_with_changeset_different_with_diff (0.00s)
        commander.go:122: 4) expected: 'git diff --color -- file1 file2', called: 'git diff -- file1 file2'
FAIL
FAIL	github.com/evilmartians/lefthook/v2/internal/run/controller	0.039s
?   	github.com/evilmartians/lefthook/v2/internal/run/controller/command	[no test files]
ok  	github.com/evilmartians/lefthook/v2/internal/run/controller/command/replacer	1.016s
ok  	github.com/evilmartians/lefthook/v2/internal/run/controller/exec	1.658s
ok  	github.com/evilmartians/lefthook/v2/internal/run/controller/filter	1.015s
ok  	github.com/evilmartians/lefthook/v2/internal/run/controller/utils	1.010s
ok  	github.com/evilmartians/lefthook/v2/internal/run/result	1.020s
ok  	github.com/evilmartians/lefthook/v2/internal/system	1.012s
?   	github.com/evilmartians/lefthook/v2/internal/templates	[no test files]
ok  	github.com/evilmartians/lefthook/v2/internal/updater	1.028s
ok  	github.com/evilmartians/lefthook/v2/internal/version	1.016s
ok  	github.com/evilmartians/lefthook/v2/tests/helpers/cmdtest	1.014s
ok  	github.com/evilmartians/lefthook/v2/tests/helpers/configtest	1.016s
ok  	github.com/evilmartians/lefthook/v2/tests/helpers/gittest	1.017s
?   	github.com/evilmartians/lefthook/v2/tests/helpers/loggertest	[no test files]
FAIL
make: *** [Makefile:25: test] Error 1
```